"""init_postgres

Revision ID: dca83c921a16
Revises: 
Create Date: 2026-02-11 10:56:53.020216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dca83c921a16'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('patronymic', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_telegram_id'), 'employees', ['telegram_id'], unique=True)
    op.create_table('absence_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_absence_request_dates', 'absence_requests', ['start_date', 'end_date'], unique=False)
    op.create_index('idx_absence_request_employee_dates', 'absence_requests', ['employee_id', 'start_date', 'end_date'], unique=False)
    op.create_index('idx_absence_request_status', 'absence_requests', ['status'], unique=False)
    op.create_index(op.f('ix_absence_requests_id'), 'absence_requests', ['id'], unique=False)
    op.create_table('invite_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_invite_code_active', 'invite_codes', ['code', 'is_used', 'expires_at'], unique=False)
    op.create_index(op.f('ix_invite_codes_id'), 'invite_codes', ['id'], unique=False)
    op.create_table('absence_request_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['absence_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_absence_request_history_request', 'absence_request_history', ['request_id', 'changed_at'], unique=False)
    op.create_index('idx_absence_request_history_type', 'absence_request_history', ['change_type', 'changed_at'], unique=False)
    op.create_index(op.f('ix_absence_request_history_id'), 'absence_request_history', ['id'], unique=False)
    op.create_table('admin_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['absence_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_active', 'admin_notifications', ['admin_id', 'is_active', 'created_at'], unique=False)
    op.create_index(op.f('ix_admin_notifications_id'), 'admin_notifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_notifications_id'), table_name='admin_notifications')
    op.drop_index('idx_notification_active', table_name='admin_notifications')
    op.drop_table('admin_notifications')
    op.drop_index(op.f('ix_absence_request_history_id'), table_name='absence_request_history')
    op.drop_index('idx_absence_request_history_type', table_name='absence_request_history')
    op.drop_index('idx_absence_request_history_request', table_name='absence_request_history')
    op.drop_table('absence_request_history')
    op.drop_index(op.f('ix_invite_codes_id'), table_name='invite_codes')
    op.drop_index('idx_invite_code_active', table_name='invite_codes')
    op.drop_table('invite_codes')
    op.drop_index(op.f('ix_absence_requests_id'), table_name='absence_requests')
    op.drop_index('idx_absence_request_status', table_name='absence_requests')
    op.drop_index('idx_absence_request_employee_dates', table_name='absence_requests')
    op.drop_index('idx_absence_request_dates', table_name='absence_requests')
    op.drop_table('absence_requests')
    op.drop_index(op.f('ix_employees_telegram_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
